name: CI/CD deploy master
on: 
  #push:
  #  branches: [ "master"]
  pull_request:
    branches: [ "master"]
jobs:
  ci_cd_deploy_master:
    runs-on: ubuntu-latest

    steps:
      - run: ls -la
      - uses: actions/checkout@v2
      - run: ls -la
      - run: git branch   
     # - run: git checkout deploy-release   
      
      - run: echo 'hello universe'
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: install dependencies 
        run: npm ci

      - name: build setup
        run: npm run build

      - name: list dir
        run: ls -la dist/mycv/browser
